// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using QTPlugin.Interop;
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  public struct Address
  {
    public byte[] ITEMIDLIST;
    public string Path;
    public Address(IntPtr pidl, string path)
    {
      this.ITEMIDLIST = PInvoke.GetIDListData(pidl);
      this.Path = path;
    }
    
    public Address(IntPtr pidl)
    {
      this.ITEMIDLIST = PInvoke.GetIDListData(pidl);
      this.Path = null;
    }
    
    public Address(string path)
    {
      this.ITEMIDLIST = null;
      this.Path = path;
    }
    
    public Address(byte[] idl, string path)
    {
      this.ITEMIDLIST = idl;
      this.Path = path;
    }
  }
}
