// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public enum Commands
  {
    GoBack,
    GoForward,
    GoUpOneLevel,
    RefreshBrowser,
    CloseCurrentTab,
    CloseLeft,
    CloseRight,
    CloseAllButCurrent,
    CloseAllButOne,
    CloseWindow,
    UndoClose,
    BrowseFolder,
    ToggleTopMost,
    FocusFileList,
    OpenTabBarOptionDialog,
    OpenButtonBarOptionDialog,
    IsFolderTreeVisible,
    IsButtonBarVisible,
    ShowFolderTree,
    ShowButtonBar,
    MD5,
    ShowProperties,
    SetModalState,
    SetSearchBoxStr,
    ReorderTabsByName,
    ReorderTabsByPath,
    ReorderTabsByActv,
    ReorderTabsRevers
  }
}
