// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public static class CONSTANTS
  {
    public const string REGISTRY_PLUGIN = @"Software\Quizo\QTTabBar\Plugins";
    public const string REGISTRY_PLUGINSETTINGS = @"Software\Quizo\QTTabBar\Plugins\Settings";
  }
}
