// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  using System.Drawing;
  
  public interface IBarButton : IPluginClient
  {
    Image GetImage(bool fLarge);
    void InitializeItem();
    void OnButtonClick();
    
    bool ShowTextLabel { get; }
    
    string Text { get; }
  }
}
