// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  using System.Drawing;
  using System.Windows.Forms;
  
  public interface IBarMultipleCustomItems : IPluginClient
  {
    ToolStripItem CreateItem(bool fLarge, DisplayStyle displayStyle, int index);
    Image GetImage(bool fLarge, int index);
    string GetName(int index);
    void Initialize(int[] order);
    
    int Count { get; }
  }
}
