// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  using System.Windows.Forms;
  
  public interface IBarCustomItem : IPluginClient
  {
    ToolStripItem CreateItem(bool fLarge, DisplayStyle displayStyle);
  }
}
