// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  using System.Windows.Forms;
  
  public interface IBarDropButton : IBarButton, IPluginClient
  {
    void OnDropDownItemClick(ToolStripItem item, MouseButtons mouseButton);
    void OnDropDownOpening(ToolStripDropDownMenu menu);
    
    bool IsSplitButton { get; }
  }
}
