// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  using System.Text;
  
  public interface IEncodingDetector : IPluginClient
  {
    Encoding GetEncoding(ref byte[] data);
  }
}
