// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  using System.Runtime.InteropServices;
  using System.Text.RegularExpressions;
  
  public interface IFilter : IPluginClient
  {
    bool QueryRegex(string strQuery, out Regex re);
  }
}
