// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using QTPlugin.Interop;
  using System;
  using System.Runtime.InteropServices;
  
  public interface IPluginClient
  {
    void Close(EndCode endCode);
    void OnMenuItemClick(MenuType menuType, string menuText, ITab tab);
    void OnOption();
    void OnShortcutKeyPressed(int index);
    void Open(IPluginServer pluginServer, IShellBrowser shellBrowser);
    bool QueryShortcutKeys(out string[] actions);
    
    bool HasOption { get; }
  }
}
