// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  using System.Diagnostics;
  using System.Drawing;
  using System.Runtime.CompilerServices;
  using System.Runtime.InteropServices;
  using System.Windows.Forms;
  
  public interface IPluginServer
  {
    event PluginEventHandler ExplorerStateChanged;
    
    event EventHandler MenuRendererChanged;
    
    event EventHandler MouseEnter;
    
    event EventHandler MouseLeave;
    
    event PluginEventHandler NavigationComplete;
    
    event PluginEventHandler PointedTabChanged;
    
    event PluginEventHandler SelectionChanged;
    
    event PluginEventHandler SettingsChanged;
    
    event PluginEventHandler TabAdded;
    
    event PluginEventHandler TabChanged;
    
    event PluginEventHandler TabRemoved;
    
    bool AddApplication(string name, ProcessStartInfo startInfo);
    bool AddGroup(string groupName, string[] paths);
    bool CreateTab(Address address, int index, bool fLocked, bool fSelect);
    bool CreateWindow(Address address);
    bool ExecuteCommand(Commands command, object arg);
    ProcessStartInfo[] GetApplications(string name);
    string[] GetGroupPaths(string groupName);
    ToolStripRenderer GetMenuRenderer();
    ITab[] GetTabs();
    ITab HitTest(Point pnt);
    void OpenGroup(string[] groupNames);
    void RegisterMenu(IPluginClient pluginClient, MenuType menuType, string menuText, bool fRegister);
    bool RemoveApplication(string name);
    bool RemoveGroup(string groupName);
    bool TryGetLocalizedStrings(IPluginClient pluginClient, int count, out string[] arrStrings);
    bool TryGetSelection(out Address[] selectedItems);
    bool TrySetSelection(Address[] itemsToSelect, bool fDeselectOthers);
    void UpdateItem(IBarButton barItem, bool fEnabled, bool fRefreshImage);
    
    IntPtr ExplorerHandle { get; }
    
    string[] Groups { get; }
    
    IntPtr Handle { get; }
    
    ITab SelectedTab { get; set; }
    
    QTPlugin.TabBarOption TabBarOption { get; set; }
  }
}
