// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public abstract class LocalizedStringProvider
  {
    protected LocalizedStringProvider()
    {
    }
    
    public abstract void SetKey(int iKey);
    
    public abstract string Author { get; }
    
    public abstract string Description { get; }
    
    public abstract string Name { get; }
  }
}
