// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  using System.Runtime.CompilerServices;
  
  public delegate void PluginEventHandler(object sender, PluginEventArgs e);
}
