// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public enum PluginType
  {
    Interactive,
    Background,
    BackgroundMultiple,
    Static
  }
}
