// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public sealed class PluginEventArgs : EventArgs
  {
    private QTPlugin.Address address;
    private int index;
    private ExplorerWindowActions windowAction;
    
    public PluginEventArgs(ExplorerWindowActions windowAction)
    {
      this.windowAction = windowAction;
    }
    
    public PluginEventArgs(int index, QTPlugin.Address address)
    {
      this.index = index;
      this.address = address;
    }
    
    public QTPlugin.Address Address
    {
      get
      {
        return this.address;
      }
    }
    
    public int Index
    {
      get
      {
        return this.index;
      }
    }
    
    public ExplorerWindowActions WindowAction
    {
      get
      {
        return this.windowAction;
      }
    }
  }
}
