// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public enum TabBar_Options_Boolean
  {
    ActivateNew,
    ReuseTab,
    CloseAllOnGroup,
    Tooltip,
    XButtons,
    NavButtons,
    TabHistory,
    RecentFiles,
    DragDrop,
    RenameAmbiguous,
    MiddleClickFolder,
    UpOneLevelOnDblClick,
    NoWindowResize,
    SaveTransparency,
    CaptureProcess,
    ShowFolderTreeOnNewProcess,
    NoCaptureWindow,
    HScrollShiftWheel,
    ChangeViewModeCtrlWheel,
    NoCloseWindow,
    NoCloseLocked,
    RestoreTabs,
    RestoreLocked,
    UseTabSkin,
    ShowFolderIcon,
    ActiveTabFontBold,
    DrawToolBarBackground,
    HideMenuBar,
    XPCompatibleBSKey,
    FullRowSelect,
    GridLines,
    ListViewAlternateColor,
    ShowPreviewTip,
    PreviewTipMode_ShiftKey,
    ShowSubDirTip,
    SubDirTipMode_ShiftKey,
    SubDirTipMode_PreviewTip,
    SubDirTipMode_HiddenFiles,
    SubDirTipMode_SystemFiles,
    SubDirTipMode_Files,
    SelectionOnRenaming,
    SendToTrayOnClose
  }
}
