// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public enum TabBar_Options_Misc
  {
    PreviewTipTextExtensions = 0x80002,
    TabFontSize = 0x80001,
    TabSkinMargins = 0x80000
  }
}
