// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public enum TabBar_Options_Color
  {
    AlternateBackgourndColor = 0x40004,
    AlternateTextColor = 0x40003,
    ClassicHiliteColor = 0x40005,
    TabTitleActiveColor = 0x40000,
    TabTitleInctiveColor = 0x40001,
    ToolbarBackgroundColor = 0x40002
  }
}
