// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public enum TabBar_Options_Int
  {
    ActiveTabOnClose = 0x10003,
    BarDoubleClicked = 0x10005,
    MiddleClickFolderAction = 0x10007,
    MultipleRows = 0x10006,
    NavButtonPosition = 0x10000,
    NewTabLocation = 0x10002,
    PreviewTipMaxHeight = 0x1000e,
    PreviewTipMaxWidth = 0x1000d,
    TabDoubleClicked = 0x10004,
    TabHeight = 0x10008,
    TabHistoryMax = 0x10001,
    TabWidthFixed = 0x1000a,
    TabWidthMax = 0x1000b,
    TabWidthMin = 0x1000c,
    TabWidthMode = 0x10009
  }
}
