// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin
{
  using System;
  
  public enum TabBar_Options_String
  {
    BarDoubleClickedPath = 0x20001,
    LanguageFilePath = 0x20000,
    PluginLanguageFilePath = 0x20004,
    TabFontFamilyName = 0x20003,
    TabSkinPath = 0x20002
  }
}
