// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("6d5140c1-7436-11ce-8034-00aa006009fa"), SuppressUnmanagedCodeSecurity]
  internal interface _IServiceProvider
  {
    void QueryService(ref Guid guid, ref Guid riid, [MarshalAs(UnmanagedType.Interface)] out object Obj);
  }
}
