// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  
  [Flags]
  public enum DBIM : uint
  {
    ACTUAL = 8,
    BKCOLOR = 0x40,
    INTEGRAL = 4,
    MAXSIZE = 2,
    MINSIZE = 1,
    MODEFLAGS = 0x20,
    TITLE = 0x10
  }
}
