// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  
  [Flags]
  public enum DBIMF : uint
  {
    ADDTOFRONT = 0x200,
    BKCOLOR = 0x40,
    BREAK = 0x100,
    DEBOSSED = 0x20,
    FIXED = 1,
    FIXEDBMP = 4,
    NORMAL = 0,
    TOPALIGN = 0x400,
    UNDELETEABLE = 0x10,
    USECHEVRON = 0x80,
    VARIABLEHEIGHT = 8
  }
}
