// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  using System.Drawing;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)]
  public struct DESKBANDINFO
  {
    public DBIM dwMask;
    public Point ptMinSize;
    public Point ptMaxSize;
    public Point ptIntegral;
    public Point ptActual;
    [MarshalAs(UnmanagedType.ByValTStr, SizeConst=0xff)]
    public string wszTitle;
    public DBIMF dwModeFlags;
    public int crBkgnd;
  }
}
