// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("EB0FE172-1A3A-11D0-89B3-00A0C90A90AC"), SuppressUnmanagedCodeSecurity]
  internal interface IDeskBand
  {
    void GetWindow(out IntPtr phwnd);
    void ContextSensitiveHelp([In] bool fEnterMode);
    void ShowDW([In] bool fShow);
    void CloseDW([In] uint dwReserved);
    void ResizeBorderDW(IntPtr prcBorder, [In, MarshalAs(UnmanagedType.IUnknown)] object punkToolbarSite, bool fReserved);
    void GetBandInfo(uint dwBandID, uint dwViewMode, ref DESKBANDINFO pdbi);
  }
}
