// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, Guid("012dd920-7b26-11d0-8ca9-00a0c92dbfe8"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown), SuppressUnmanagedCodeSecurity]
  internal interface IDockingWindow
  {
    void GetWindow(out IntPtr phwnd);
    void ContextSensitiveHelp([In] bool fEnterMode);
    void ShowDW([In] bool fShow);
    void CloseDW([In] uint dwReserved);
    void ResizeBorderDW(IntPtr prcBorder, [In, MarshalAs(UnmanagedType.IUnknown)] object punkToolbarSite, bool fReserved);
  }
}
