// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("68284faa-6a48-11d0-8c78-00c04fd918b4"), SuppressUnmanagedCodeSecurity]
  internal interface IInputObject
  {
    void UIActivateIO(int fActivate, ref MSG msg);
    [PreserveSig]
    int HasFocusIO();
    [PreserveSig]
    int TranslateAcceleratorIO(ref MSG msg);
  }
}
