// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, SuppressUnmanagedCodeSecurity, Guid("f1db8392-7331-11d0-8c99-00a0c92dbfe8"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
  public interface IInputObjectSite
  {
    [PreserveSig]
    int OnFocusChangeIS([MarshalAs(UnmanagedType.IUnknown)] object punkObj, int fSetFocus);
  }
}
