// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("00000114-0000-0000-C000-000000000046"), SuppressUnmanagedCodeSecurity]
  internal interface IOleWindow
  {
    void GetWindow(out IntPtr phwnd);
    void ContextSensitiveHelp([In] bool fEnterMode);
  }
}
