// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace BandObjectLib
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, Guid("00000109-0000-0000-C000-000000000046"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown), SuppressUnmanagedCodeSecurity]
  internal interface IPersistStream
  {
    void GetClassID(out Guid pClassID);
    [PreserveSig]
    int IsDirty();
    void IPersistStreamLoad([In, MarshalAs(UnmanagedType.Interface)] object pStm);
    void Save([In, MarshalAs(UnmanagedType.Interface)] IntPtr pStm, [In, MarshalAs(UnmanagedType.Bool)] bool fClearDirty);
    [PreserveSig]
    int GetSizeMax(out ulong pcbSize);
  }
}
