// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using BandObjectLib;
  using System;
  using System.Runtime.InteropServices;
  using System.Runtime.InteropServices.ComTypes;
  using System.Security;
  using System.Windows.Forms;
  
  [ComImport, Guid("00000122-0000-0000-C000-000000000046"), SuppressUnmanagedCodeSecurity, InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
  internal interface _IDropTarget
  {
    [PreserveSig]
    int DragEnter(System.Runtime.InteropServices.ComTypes.IDataObject pDataObj, int grfKeyState, BandObjectLib.POINT pt, ref DragDropEffects pdwEffect);
    [PreserveSig]
    int DragOver(int grfKeyState, BandObjectLib.POINT pt, ref DragDropEffects pdwEffect);
    [PreserveSig]
    int DragLeave();
    [PreserveSig]
    int DragDrop(System.Runtime.InteropServices.ComTypes.IDataObject pDataObj, int grfKeyState, BandObjectLib.POINT pt, ref DragDropEffects pdwEffect);
  }
}
