// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.CompilerServices;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, SuppressUnmanagedCodeSecurity, ClassInterface(ClassInterfaceType.None), Guid("00021401-0000-0000-C000-000000000046")]
  internal class _ShellLinkObject
  {
  }
}
