// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct CMINVOKECOMMANDINFO
  {
    public int cbSize;
    public int fMask;
    public IntPtr hwnd;
    public IntPtr lpVerb;
    public IntPtr lpParameters;
    public IntPtr lpDirectory;
    public int nShow;
    public int dwHotKey;
    public IntPtr hIcon;
  }
}
