// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct COPYDATASTRUCT
  {
    public IntPtr dwData;
    public int cbData;
    public IntPtr lpData;
  }
}
