// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct CWPSTRUCT
  {
    public IntPtr lParam;
    public IntPtr wParam;
    public uint message;
    public IntPtr hwnd;
  }
}
