// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct DEV_BROADCAST_HDR
  {
    public int dbch_size;
    public int dbch_devicetype;
    public int dbch_reserved;
  }
}
