// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct DEV_BROADCAST_VOLUME
  {
    public int dbcv_size;
    public int dbcv_devicetype;
    public int dbcv_reserved;
    public uint dbcv_unitmask;
    public short dbcv_flags;
  }
}
