// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Drawing;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential, Pack=1)]
  internal struct DROPFILES
  {
    public int pFiles;
    public Point pt;
    public bool fNC;
    public bool fWide;
  }
}
