// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Drawing;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct DTTOPTS
  {
    public int dwSize;
    public uint dwFlags;
    public uint crText;
    public uint crBorder;
    public uint crShadow;
    public int iTextShadowType;
    public Point ptShadowOffset;
    public int iBorderSize;
    public int iFontPropId;
    public int iColorPropId;
    public int iStateId;
    public int fApplyOverlay;
    public int iGlowSize;
    public IntPtr pfnDrawTextCallback;
    public IntPtr lParam;
  }
}
