// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.CompilerServices;
  
  internal delegate bool EnumWndProc(IntPtr hwnd, IntPtr lParam);
}
