// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  
  internal enum FolderViewMode
  {
    FVM_DETAILS = 4,
    FVM_ICON = 1,
    FVM_LIST = 3,
    FVM_THUMBNAIL = 5,
    FVM_THUMBSTRIP = 7,
    FVM_TILE = 6
  }
}
