// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct HDITEM
  {
    public int mask;
    public int cxy;
    public IntPtr pszText;
    public IntPtr hbm;
    public int cchTextMax;
    public int fmt;
    public IntPtr lParam;
    public int iImage;
    public int iOrder;
    public int type;
    public IntPtr pvFilter;
    public int state;
  }
}
