// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, Guid("000214F4-0000-0000-c000-000000000046"), SuppressUnmanagedCodeSecurity, InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
  internal interface IContextMenu2
  {
    [PreserveSig]
    int QueryContextMenu(IntPtr hMenu, uint indexMenu, uint idCmdFirst, uint idCmdLast, uint uFlags);
    [PreserveSig]
    int InvokeCommand(ref CMINVOKECOMMANDINFO pici);
    void GetCommandString(uint idCmd, uint uFlags, ref int pwReserved, IntPtr commandstring, uint cch);
    [PreserveSig]
    int HandleMenuMsg(int uMsg, IntPtr wParam, IntPtr lParam);
  }
}
