// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using BandObjectLib;
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, SuppressUnmanagedCodeSecurity, Guid("79D16DE4-ABEE-4021-8D9D-9169B261D657"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
  internal interface IDeskBand2
  {
    void GetWindow(out IntPtr phwnd);
    void ContextSensitiveHelp([In] bool fEnterMode);
    void ShowDW([In] bool fShow);
    void CloseDW([In] uint dwReserved);
    void ResizeBorderDW(IntPtr prcBorder, [In, MarshalAs(UnmanagedType.IUnknown)] object punkToolbarSite, bool fReserved);
    void GetBandInfo(uint dwBandID, uint dwViewMode, ref DESKBANDINFO pdbi);
    void CanRenderComposited(out bool pfCanRenderComposited);
    void SetCompositionState(bool fCompositionEnabled);
    void GetCompositionState(out bool pfCompositionEnabled);
  }
}
