// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), SuppressUnmanagedCodeSecurity, Guid("7EBFDD85-AD18-11d3-A4C5-00C04F72D6B8")]
  internal interface IEnumTravelLogEntry
  {
    [PreserveSig]
    int Next([In] uint cElt, [MarshalAs(UnmanagedType.Interface)] out ITravelLogEntry rgElt, [Out] uint pcEltFetched);
    [PreserveSig]
    int Skip([In] uint cElt);
    [PreserveSig]
    int Reset();
    [PreserveSig]
    int Clone([MarshalAs(UnmanagedType.Interface)] out IEnumTravelLogEntry ppEnum);
  }
}
