// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, Guid("000214F2-0000-0000-C000-000000000046"), SuppressUnmanagedCodeSecurity, InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
  internal interface IEnumIDList
  {
    [PreserveSig]
    int Next(uint celt, out IntPtr rgelt, object pceltFetched);
    void Skip(uint celt);
    void Reset();
    void Clone(out IEnumIDList ppenum);
  }
}
