// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Drawing;
  using System.Runtime.InteropServices;
  using System.Security;
  using System.Text;
  
  [ComImport, SuppressUnmanagedCodeSecurity, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("BB2E617C-0920-11d1-9A0B-00C04FC2D6C1")]
  internal interface IExtractImage
  {
    [PreserveSig]
    int GetLocation(StringBuilder pszPathBuffer, int cch, ref int pdwPriority, ref Size prgSize, int dwRecClrDepth, ref int pdwFlags);
    [PreserveSig]
    int Extract(out IntPtr phBmpThumbnail);
  }
}
