// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using BandObjectLib;
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, SuppressUnmanagedCodeSecurity, Guid("cde725b0-ccc9-4519-917e-325d72fab4ce"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
  internal interface IFolderView
  {
    [PreserveSig]
    int GetCurrentViewMode(ref int pViewMode);
    [PreserveSig]
    int SetCurrentViewMode(int ViewMode);
    [PreserveSig]
    int GetFolder(ref Guid riid, out IPersistFolder2 ppv);
    [PreserveSig]
    int Item(int iItemIndex, out IntPtr ppidl);
    [PreserveSig]
    int ItemCount(uint uFlags, out int pcItems);
    [PreserveSig]
    int Items(uint uFlags, ref Guid riid, out IEnumIDList ppv);
    [PreserveSig]
    int GetSelectionMarkedItem(out int piItem);
    [PreserveSig]
    int GetFocusedItem(out int piItem);
    [PreserveSig]
    int GetItemPosition(IntPtr pidl, out POINT ppt);
    [PreserveSig]
    int GetSpacing(ref POINT ppt);
    [PreserveSig]
    int GetDefaultSpacing(ref POINT ppt);
    [PreserveSig]
    int GetAutoArrange();
    [PreserveSig]
    int SelectItem(int iItem, uint dwFlags);
    [PreserveSig]
    int SelectAndPositionItems(uint cidl, IntPtr apidl, IntPtr apt, int dwFlags);
  }
}
