// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, SuppressUnmanagedCodeSecurity, Guid("1AC3D9F0-175C-11d1-95BE-00609797EA4F"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
  internal interface IPersistFolder2
  {
    void GetClassID(out Guid pClassID);
    void Initialize(IntPtr pidl);
    [PreserveSig]
    int GetCurFolder(out IntPtr ppidl);
  }
}
