// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Drawing;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), SuppressUnmanagedCodeSecurity, Guid("091162a4-bc96-411f-aae8-c5122cd03363")]
  internal interface ISharedBitmap
  {
    [PreserveSig]
    int GetSharedBitmap(out IntPtr phbm);
    [PreserveSig]
    int GetSize(out Size pSize);
    [PreserveSig]
    int GetFormat(out uint pat);
    [PreserveSig]
    int InitializeBitmap(IntPtr hbm, uint wtsAT);
    [PreserveSig]
    int Detach(out IntPtr phbm);
  }
}
