// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, Guid("43826d1e-e718-42ee-bc55-a1e261c37bfe"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown), SuppressUnmanagedCodeSecurity]
  internal interface IShellItem
  {
    [PreserveSig]
    int BindToHandler(IntPtr pbc, [In] ref Guid bhid, [In] ref Guid riid, out IntPtr ppvOut);
    [PreserveSig]
    int GetParent(out IShellItem ppsi);
    [PreserveSig]
    int GetDisplayName(int sigdnName, [MarshalAs(UnmanagedType.LPWStr)] out string ppszName);
    [PreserveSig]
    int GetAttributes(int sfgaoMask, out int psfgaoAttribs);
    [PreserveSig]
    int Compare(IShellItem psi, int hint, out int piOrder);
  }
}
