// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using BandObjectLib;
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, Guid("000214E3-0000-0000-C000-000000000046"), SuppressUnmanagedCodeSecurity, InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
  internal interface IShellView
  {
    void GetWindow(out IntPtr phwnd);
    void ContextSensitiveHelp(bool fEnterMode);
    void TranslateAccelerator(ref MSG pmsg);
    void EnableModeless(bool fEnable);
    void UIActivate(uint uState);
    void Refresh();
    [PreserveSig]
    int CreateViewWindow(IShellView psvPrevious, ref FOLDERSETTINGS lpfs, IShellBrowser psb, ref RECT prcView, out IntPtr phWnd);
    void DestroyViewWindow();
    [PreserveSig]
    int GetCurrentInfo(ref FOLDERSETTINGS lpfs);
    void AddPropertySheetPages(int dwReserved, IntPtr pfn, IntPtr lparam);
    [PreserveSig]
    int SaveViewState();
    [PreserveSig]
    int SelectItem(IntPtr pidlItem, uint uFlags);
    void GetItemObject(uint uItem, ref Guid riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppv);
  }
}
