// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, Guid("56FDF342-FD6D-11d0-958A-006097C9A090"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown), SuppressUnmanagedCodeSecurity]
  internal interface ITaskbarList
  {
    [PreserveSig]
    int HrInit();
    [PreserveSig]
    int AddTab(IntPtr hwnd);
    [PreserveSig]
    int DeleteTab(IntPtr hwnd);
    [PreserveSig]
    int ActivateTab(IntPtr hwnd);
    [PreserveSig]
    int SetActiveAlt(IntPtr hwnd);
  }
}
