// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("7EBFDD87-AD18-11d3-A4C5-00C04F72D6B8"), SuppressUnmanagedCodeSecurity]
  internal interface ITravelLogEntry
  {
    [PreserveSig]
    int GetTitle(out IntPtr ppszTitle);
    [PreserveSig]
    int GetURL(out IntPtr ppszURL);
  }
}
