// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, Guid("7EBFDD80-AD18-11d3-A4C5-00C04F72D6B8"), SuppressUnmanagedCodeSecurity, InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
  internal interface ITravelLogStg
  {
    [PreserveSig]
    int CreateEntry([In, MarshalAs(UnmanagedType.BStr)] string pszUrl, [In, MarshalAs(UnmanagedType.BStr)] string pszTitle, [In, MarshalAs(UnmanagedType.Interface)] ITravelLogEntry ptleRelativeTo, [In] bool fPrepend, [MarshalAs(UnmanagedType.Interface)] out ITravelLogEntry pptle);
    [PreserveSig]
    int TravelTo([In, MarshalAs(UnmanagedType.Interface)] ITravelLogEntry ptle);
    [PreserveSig]
    int EnumEntries([In] int flags, [MarshalAs(UnmanagedType.Interface)] out IEnumTravelLogEntry ppenum);
    [PreserveSig]
    int FindEntries([In] int flags, [In, MarshalAs(UnmanagedType.BStr)] string pszUrl, [MarshalAs(UnmanagedType.Interface)] out IEnumTravelLogEntry ppenum);
    [PreserveSig]
    int GetCount([In] int flags, out int pcEntries);
    [PreserveSig]
    int RemoveEntry([In, MarshalAs(UnmanagedType.Interface)] ITravelLogEntry ptle);
    [PreserveSig]
    int GetRelativeEntry([In] int iOffset, [MarshalAs(UnmanagedType.Interface)] out ITravelLogEntry ptle);
  }
}
