// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.CompilerServices;
  using System.Runtime.InteropServices;
  using System.Security;
  
  [ComImport, ClassInterface(ClassInterfaceType.None), SuppressUnmanagedCodeSecurity, Guid("50EF4544-AC9F-4A8E-B21B-8A26180DB13F")]
  internal class LocalThumbnailCache
  {
  }
}
