// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using BandObjectLib;
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct LVHITTESTINFO
  {
    public POINT pt;
    public uint flags;
    public int iItem;
    public int iSubItem;
    public int iGroup;
  }
}
