// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct MOUSEHOOKSTRUCTEX
  {
    public MOUSEHOOKSTRUCT mhs;
    public int mouseData;
  }
}
