// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct NMLVODSTATECHANGE
  {
    public NMHDR hdr;
    public int iFrom;
    public int iTo;
    public uint uNewState;
    public uint uOldState;
  }
}
