// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct NMLVGETINFOTIP
  {
    public NMHDR hdr;
    public int dwFlags;
    public IntPtr pszText;
    public int cchTextMax;
    public int iItem;
    public int iSubItem;
    public IntPtr lParam;
  }
}
