// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential, Pack=1)]
  internal struct NMLVKEYDOWN
  {
    public NMHDR hdr;
    public short wVKey;
    public uint flags;
  }
}
