// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)]
  internal struct NMTTDISPINFO
  {
    public NMHDR hdr;
    public IntPtr lpszText;
    [MarshalAs(UnmanagedType.ByValTStr, SizeConst=80)]
    public string szText;
    public IntPtr hinst;
    public int uFlags;
    public IntPtr lParam;
    public IntPtr hbmp;
  }
}
