// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct REBARBANDINFO
  {
    public int cbSize;
    public int fMask;
    public int fStyle;
    public int clrFore;
    public int clrBack;
    public IntPtr lpText;
    public int cch;
    public int iImage;
    public IntPtr hwndChild;
    public int cxMinChild;
    public int cyMinChild;
    public int cx;
    public IntPtr hbmBack;
    public int wID;
    public int cyChild;
    public int cyMaxChild;
    public int cyIntegral;
    public int cxIdeal;
    public IntPtr lParam;
    public int cxHeader;
  }
}
