// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Drawing;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct RECT
  {
    public int left;
    public int top;
    public int right;
    public int bottom;
    public int Width
    {
      get
      {
        return Math.Abs((int) (this.right - this.left));
      }
    }
    public int Height
    {
      get
      {
        return (this.bottom - this.top);
      }
    }
    public Rectangle ToRectangle()
    {
      return new Rectangle(this.left, this.top, Math.Abs((int) (this.right - this.left)), this.bottom - this.top);
    }
  }
}
