// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)]
  internal struct SHELLEXECUTEINFO
  {
    public int cbSize;
    public int fMask;
    public IntPtr hwnd;
    public IntPtr lpVerb;
    public IntPtr lpFile;
    public IntPtr lpParameters;
    public IntPtr lpDirectory;
    public int nShow;
    public IntPtr hInstApp;
    public IntPtr lpIDList;
    public IntPtr lpClass;
    public IntPtr hkeyClass;
    public int dwHotKey;
    public IntPtr hIconhMonitor;
    public IntPtr hProcess;
  }
}
