// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)]
  internal struct SHFILEOPSTRUCT64
  {
    public IntPtr hwnd;
    public int wFunc;
    public IntPtr pFrom;
    public IntPtr pTo;
    public short fFlags;
    public bool fAnyOperationsAborted;
    public IntPtr hNameMappings;
    public IntPtr lpszProgressTitle;
  }
}
