// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Explicit, Size=260)]
  internal struct STRRETinternal
  {
    [FieldOffset(0)]
    public IntPtr cStr;
    [FieldOffset(0)]
    public IntPtr pOleStr;
    [FieldOffset(0)]
    public IntPtr pStr;
    [FieldOffset(0)]
    public uint uOffset;
  }
}
