// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct TRACKMOUSEEVENT
  {
    public int cbSize;
    public int dwFlags;
    public IntPtr hwndTrack;
    public uint dwHoverTime;
  }
}
