// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct WTS_THUMBNAILID
  {
    [MarshalAs(UnmanagedType.ByValArray, SizeConst=0x10)]
    public byte[] rgbKey;
  }
}
