// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Windows.Forms;
  
  internal sealed class DataGridViewEx : DataGridView
  {
    public DataGridViewEx()
    {
      base.DoubleBuffered = true;
    }
  }
}
