// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Drawing;
  using System.Drawing.Imaging;
  using System.Windows.Forms;
  
  internal sealed class DefaultMenuRenderer : ToolStripProfessionalRenderer
  {
    protected override void OnRenderItemImage(ToolStripItemImageRenderEventArgs e)
    {
      QMenuItem item = e.Item as QMenuItem;
      if (((item != null) && item.IsCut) && ((e.ImageRectangle != Rectangle.Empty) && (e.Image != null)))
      {
        ColorMatrix newColorMatrix = new ColorMatrix();
        using (ImageAttributes attributes = new ImageAttributes())
        {
          newColorMatrix.Matrix33 = 0.5f;
          attributes.SetColorMatrix(newColorMatrix);
          Size size = e.Image.Size;
          e.Graphics.DrawImage(e.Image, e.ImageRectangle, 0, 0, size.Width, size.Height, GraphicsUnit.Pixel, attributes);
          return;
        }
      }
      base.OnRenderItemImage(e);
    }
    
    protected override void OnRenderItemText(ToolStripItemTextRenderEventArgs e)
    {
      e.TextFormat |= TextFormatFlags.NoPrefix;
      base.OnRenderItemText(e);
    }
  }
}
