// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  
  internal sealed class DirectoryMenuItem : QMenuItem
  {
    private DateTime dtDirMod;
    private QTTabBarLib.EventPack ep;
    public bool OnceOpened;
    
    public DirectoryMenuItem(string text) : base(text, MenuTarget.Folder, MenuGenre.Application)
    {
    }
    
    public QTTabBarLib.EventPack EventPack
    {
      get
      {
        return this.ep;
      }
      set
      {
        this.ep = value;
      }
    }
    
    public DateTime ModifiiedDate
    {
      get
      {
        return this.dtDirMod;
      }
      set
      {
        this.dtDirMod = value;
      }
    }
  }
}
