// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  
  internal enum HashCalcStatus
  {
    None,
    Calculating,
    Finished,
    Aborted
  }
}
