// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  
  internal sealed class ImageReservationKey
  {
    private int iReservedType;
    private string reservedKey;
    
    public ImageReservationKey(string key, int iReservedType)
    {
      this.reservedKey = key;
      this.iReservedType = iReservedType;
    }
    
    public string ImageKey
    {
      get
      {
        return this.reservedKey;
      }
    }
    
    public int ImageType
    {
      get
      {
        return this.iReservedType;
      }
    }
  }
}
