// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Drawing;
  using System.Windows.Forms;
  
  internal sealed class ItemRightClickedEventArgs
  {
    private ToolStripItem clickedItem;
    private int hresult;
    private bool isKey;
    private System.Drawing.Point pnt;
    
    public ItemRightClickedEventArgs(ToolStripItem clickedItem, bool fKey, System.Drawing.Point pnt)
    {
      this.clickedItem = clickedItem;
      this.isKey = fKey;
      this.pnt = pnt;
    }
    
    public ToolStripItem ClickedItem
    {
      get
      {
        return this.clickedItem;
      }
    }
    
    public int HRESULT
    {
      get
      {
        return this.hresult;
      }
      set
      {
        this.hresult = value;
      }
    }
    
    public bool IsKey
    {
      get
      {
        return this.isKey;
      }
    }
    
    public System.Drawing.Point Point
    {
      get
      {
        return this.pnt;
      }
    }
  }
}
