// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.IO;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  internal struct LogData : IEquatable<LogData>
  {
    public string Path;
    public byte[] IDL;
    public int Hash;
    public LogData(string path, byte[] idl, int hash)
    {
      this.Path = path;
      this.IDL = idl;
      this.Hash = hash;
    }
    
    public bool Equals(LogData other)
    {
      if (!string.Equals(this.Path, other.Path, StringComparison.OrdinalIgnoreCase))
      {
        return false;
      }
      return (System.IO.Path.IsPathRooted(this.Path) || (this.Hash == other.Hash));
    }
  }
}
