// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Collections.Generic;
  using System.Drawing;
  
  public sealed class MemoForm
  {
    [Serializable]
    public sealed class MemoStore
    {
      private Rectangle _bounds;
      private Dictionary<string, string> _dic;
      private double _opacity;
      private Dictionary<string, string> _txtDic;
      
      public Rectangle Bounds
      {
        get
        {
          return this._bounds;
        }
        set
        {
          this._bounds = value;
        }
      }
      
      public Dictionary<string, string> Dictionary
      {
        get
        {
          return this._dic;
        }
        set
        {
          this._dic = value;
        }
      }
      
      public double Opacity
      {
        get
        {
          return this._opacity;
        }
        set
        {
          this._opacity = value;
        }
      }
      
      public Dictionary<string, string> TxtDictionary
      {
        get
        {
          return this._txtDic;
        }
        set
        {
          this._txtDic = value;
        }
      }
    }
  }
}
