// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  
  internal enum MenuGenre
  {
    Navigation,
    Branch,
    History,
    Group,
    Application,
    SubDirTip,
    RecentFile
  }
}
