// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Runtime.CompilerServices;
  using System.Windows.Forms;
  
  internal delegate void MenuReorderedEventHandler(object sender, ToolStripItemClickedEventArgs e);
}
