// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Runtime.CompilerServices;
  using System.Windows.Forms;
  
  internal sealed class NativeWindowControler : NativeWindow
  {
    private IntPtr hwndOptional;
    
    internal event MessageEventHandler MessageCaptured;
    
    public NativeWindowControler(IntPtr hwnd)
    {
      base.AssignHandle(hwnd);
    }
    
    protected override void WndProc(ref Message m)
    {
      if ((this.MessageCaptured == null) || !this.MessageCaptured(ref m))
      {
        base.WndProc(ref m);
      }
    }
    
    public IntPtr OptionalHandle
    {
      get
      {
        return this.hwndOptional;
      }
      set
      {
        this.hwndOptional = value;
      }
    }
    
    internal delegate bool MessageEventHandler(ref Message msg);
  }
}
