// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  
  internal sealed class PathData
  {
    public string strDisplay;
    public string strImageKey;
    public string strPath;
    
    public PathData(string strDisplay, string strPath, string strImageKey)
    {
      this.strDisplay = strDisplay;
      this.strPath = strPath;
      this.strImageKey = strImageKey;
    }
  }
}
