// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Runtime.CompilerServices;
  
  internal delegate void PluginOptionEventHandler(object sender, PluginOptionEventArgs e);
}
