// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using QTPlugin;
  using System;
  
  internal sealed class Plugin
  {
    private bool fBackgroundButtonIsEnabled;
    private bool fBackgroundButtonIsSupported;
    private IPluginClient pluginClient;
    private QTTabBarLib.PluginInformation pluginInfo;
    
    public Plugin(IPluginClient pluginClient, QTTabBarLib.PluginInformation pluginInfo)
    {
      this.pluginClient = pluginClient;
      this.pluginInfo = pluginInfo;
      this.fBackgroundButtonIsSupported = ((pluginInfo.PluginType == PluginType.Background) && ((pluginClient is IBarButton) || (pluginClient is IBarCustomItem))) || ((pluginInfo.PluginType == PluginType.BackgroundMultiple) && (pluginClient is IBarMultipleCustomItems));
    }
    
    public void Close(EndCode code)
    {
      if (this.pluginClient != null)
      {
        try
        {
          this.pluginClient.Close(code);
        }
        catch (Exception exception)
        {
          PluginManager.HandlePluginException(exception, IntPtr.Zero, this.pluginInfo.Name, "Closing plugin.");
        }
        this.pluginClient = null;
      }
      this.pluginInfo = null;
    }
    
    public bool BackgroundButtonEnabled
    {
      get
      {
        return (this.fBackgroundButtonIsSupported && this.fBackgroundButtonIsEnabled);
      }
      set
      {
        if (this.fBackgroundButtonIsSupported)
        {
          this.fBackgroundButtonIsEnabled = value;
        }
      }
    }
    
    public bool BackgroundButtonSupported
    {
      get
      {
        return this.fBackgroundButtonIsSupported;
      }
    }
    
    public IPluginClient Instance
    {
      get
      {
        return this.pluginClient;
      }
    }
    
    public QTTabBarLib.PluginInformation PluginInformation
    {
      get
      {
        return this.pluginInfo;
      }
    }
  }
}
