// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Runtime.InteropServices;
  
  [Serializable, StructLayout(LayoutKind.Sequential)]
  internal struct PluginKey
  {
    public string PluginID;
    public int[] Keys;
    public PluginKey(string pluginID, int[] keys)
    {
      this.PluginID = pluginID;
      this.Keys = keys;
    }
  }
}
