// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using QTPlugin;
  using System;
  using System.Drawing;
  
  internal sealed class PluginInformation : IDisposable
  {
    public string Author;
    public string Description;
    public bool Enabled;
    public Image ImageLarge;
    public Image ImageSmall;
    public int Index;
    public string Name;
    public string Path;
    public string PluginID;
    public QTPlugin.PluginType PluginType;
    public string[] ShortcutKeyActions;
    public string TypeFullName;
    public string Version;
    
    public PluginInformation(PluginAttribute pluginAtt, string path, string pluginID, string typeFullName)
    {
      this.Author = pluginAtt.Author;
      this.Name = pluginAtt.Name;
      this.Version = pluginAtt.Version;
      this.Description = pluginAtt.Description;
      this.PluginType = pluginAtt.PluginType;
      this.Path = path;
      this.PluginID = pluginID;
      this.TypeFullName = typeFullName;
    }
    
    public PluginInformation Clone(int index)
    {
      PluginInformation information = (PluginInformation) base.MemberwiseClone();
      information.Index = index;
      return information;
    }
    
    public void Dispose()
    {
      if (this.ImageLarge != null)
      {
        this.ImageLarge.Dispose();
        this.ImageLarge = null;
      }
      if (this.ImageSmall != null)
      {
        this.ImageSmall.Dispose();
        this.ImageSmall = null;
      }
    }
  }
}
