// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Runtime.CompilerServices;
  
  internal delegate bool PluginInfoHasOption(PluginInformation pi);
}
