// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.ComponentModel;
  
  internal sealed class PluginOptionEventArgs : CancelEventArgs
  {
    private QTTabBarLib.PluginViewItem pvi;
    
    public PluginOptionEventArgs(QTTabBarLib.PluginViewItem pvi)
    {
      this.pvi = pvi;
    }
    
    public QTTabBarLib.PluginViewItem PluginViewItem
    {
      get
      {
        return this.pvi;
      }
    }
  }
}
