// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Windows.Forms;
  
  internal sealed class QEventArgs
  {
    private ArrowDirection arrowDir;
    private int rowCount;
    
    public QEventArgs(int rowCount)
    {
      this.rowCount = rowCount;
    }
    
    public QEventArgs(ArrowDirection arrowDir)
    {
      this.arrowDir = arrowDir;
    }
    
    public ArrowDirection Direction
    {
      get
      {
        return this.arrowDir;
      }
    }
    
    public int RowCount
    {
      get
      {
        return this.rowCount;
      }
    }
  }
}
