//    This file is part of QTTabBar, a shell extension for Microsoft
//    Windows Explorer.
//    Copyright (C) 2010  Paul Accisano
//
//    QTTabBar is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    QTTabBar is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with QTTabBar.  If not, see <http://www.gnu.org/licenses/>.

namespace QTTabBarLib {
    using System;
    using System.Runtime.CompilerServices;
    using System.Windows.Forms;

    internal class QMenuItem : ToolStripMenuItem {
        private string extension;
        private bool fCut;
        private bool fExistsAsserted;
        private bool fForceToolTip;
        private bool fHasIcon;
        private bool fImageLoaded;
        private bool fVirtualQueried;
        private byte[] idl;
        private byte[] idlChild;
        private ImageReservationKey imageReservationKey;
        private MenuGenre menuGenre;
        private MenuTarget menuTarget;
        private QTTabBarLib.MenuItemArguments mia;
        private string originalImageKey;
        private string originalTitle;
        private string path;
        private string pathChild;
        private string targetPath;

        public event EventHandler QueryVirtualMenu;

        public QMenuItem(string title, MenuGenre menuGenre)
            : base(title) {
            this.menuGenre = menuGenre;
        }

        public QMenuItem(string title, QTTabBarLib.MenuItemArguments mia)
            : base(title) {
            if(mia != null) {
                this.path = mia.Path;
                this.mia = mia;
                this.menuTarget = mia.Target;
                this.menuGenre = mia.Genre;
            }
        }

        public QMenuItem(string title, MenuTarget menuTarget, MenuGenre menuGenre)
            : base(title) {
            this.menuTarget = menuTarget;
            this.menuGenre = menuGenre;
        }

        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
            if((disposing && base.HasDropDownItems) && !base.DropDown.IsAutoGenerated) {
                base.DropDown.Dispose();
                base.DropDown = null;
            }
        }

        protected override void OnMouseHover(EventArgs e) {
            if(!string.IsNullOrEmpty(base.ToolTipText)) {
                DropDownMenuBase parent = base.Parent as DropDownMenuBase;
                if((parent != null) && parent.UpdateToolTip_OnTheEdge(this)) {
                    return;
                }
            }
            base.OnMouseHover(e);
        }

        protected override void OnPaint(PaintEventArgs e) {
            if(!this.fImageLoaded) {
                this.fImageLoaded = true;
                if(this.imageReservationKey != null) {
                    QTUtility.LoadReservedImage(this.imageReservationKey);
                }
            }
            if(!this.fVirtualQueried) {
                this.fVirtualQueried = true;
                if(this.QueryVirtualMenu != null) {
                    this.QueryVirtualMenu(this, EventArgs.Empty);
                    this.QueryVirtualMenu = null;
                }
            }
            base.OnPaint(e);
        }

        internal void RestoreOriginalImage() {
            if(!base.ImageKey.Equals(this.originalImageKey)) {
                base.ImageKey = this.originalImageKey;
            }
        }

        internal void RestoreOriginalImage(bool changeImageSelected, bool fForceSelectedImage) {
            if((this.mia != null) && (fForceSelectedImage || (changeImageSelected && this.Selected))) {
                if(this.mia.IsBack) {
                    if(this.mia.Index == 0) {
                        base.ImageKey = "current";
                    }
                    else {
                        base.ImageKey = "back";
                    }
                }
                else {
                    base.ImageKey = "forward";
                }
            }
            else if(!base.ImageKey.Equals(this.originalImageKey)) {
                base.ImageKey = this.originalImageKey;
            }
        }

        public void SetImageReservationKey(string path, string ext) {
            this.imageReservationKey = QTUtility.ReserveImageKey(this, path, ext);
            this.ImageKey = this.imageReservationKey.ImageKey;
            this.fImageLoaded = this.imageReservationKey.ImageKey == "folder";
        }

        public bool Exists {
            get {
                return this.fExistsAsserted;
            }
            set {
                this.fExistsAsserted = value;
            }
        }

        public virtual string Extension {
            get {
                return this.extension;
            }
            set {
                this.extension = value;
            }
        }

        public bool ForceToolTip {
            get {
                return this.fForceToolTip;
            }
            set {
                this.fForceToolTip = value;
            }
        }

        public MenuGenre Genre {
            get {
                return this.menuGenre;
            }
        }

        public bool HasIcon {
            get {
                return this.fHasIcon;
            }
            set {
                this.fHasIcon = value;
            }
        }

        public byte[] IDLData {
            get {
                return this.idl;
            }
            set {
                this.idl = value;
            }
        }

        public byte[] IDLDataChild {
            get {
                return this.idlChild;
            }
            set {
                this.idlChild = value;
            }
        }

        public string ImageKey {
            get {
                return base.ImageKey;
            }
            set {
                if(base.ImageKey.Length == 0) {
                    this.originalImageKey = value;
                }
                base.ImageKey = value;
            }
        }

        public bool IsCut {
            get {
                return this.fCut;
            }
            set {
                if(this.fCut ^ value) {
                    this.fCut = value;
                    base.Invalidate();
                }
            }
        }

        public QTTabBarLib.MenuItemArguments MenuItemArguments {
            get {
                return this.mia;
            }
            set {
                this.mia = value;
            }
        }

        public virtual string OriginalTitle {
            get {
                return this.originalTitle;
            }
            set {
                this.originalTitle = value;
            }
        }

        public virtual string Path {
            get {
                return this.path;
            }
            set {
                this.path = value;
            }
        }

        public string PathChild {
            get {
                return this.pathChild;
            }
            set {
                this.pathChild = value;
            }
        }

        public MenuTarget Target {
            get {
                return this.menuTarget;
            }
        }

        public virtual string TargetPath {
            get {
                return this.targetPath;
            }
            set {
                this.targetPath = value;
            }
        }
    }
}
