// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Windows.Forms;
  
  internal sealed class QTabCancelEventArgs : TabControlCancelEventArgs
  {
    private QTabItemBase tabPage;
    
    public QTabCancelEventArgs(QTabItemBase tabPage, int tabPageIndex, bool cancel, TabControlAction action) : base(null, tabPageIndex, cancel, action)
    {
      this.tabPage = tabPage;
    }
    
    public QTabItemBase TabPage
    {
      get
      {
        return this.tabPage;
      }
    }
  }
}
