// Generated by Reflector from c:\program files\qttabbar\QTTabBar.dll
namespace QTTabBarLib
{
  using System;
  using System.Windows.Forms;
  
  internal sealed class ToolbarRenderer : ToolStripSystemRenderer
  {
    protected override void OnRenderToolStripBorder(ToolStripRenderEventArgs e)
    {
    }
  }
}
