// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin.Interop
{
  using System;
  
  public enum FOLDERVIEWMODE
  {
    FVM_DETAILS = 4,
    FVM_ICON = 1,
    FVM_LIST = 3,
    FVM_SMALLICON = 2,
    FVM_THUMBNAIL = 5,
    FVM_THUMBSTRIP = 7,
    FVM_TILE = 6
  }
}
