// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("000214F2-0000-0000-C000-000000000046")]
  public interface IEnumIDList
  {
    [PreserveSig]
    int Next(uint celt, out IntPtr rgelt, out IntPtr pceltFetched);
    [PreserveSig]
    int Skip(uint celt);
    [PreserveSig]
    int Reset();
    [PreserveSig]
    int Clone(out IEnumIDList ppenum);
  }
}
