// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("cde725b0-ccc9-4519-917e-325d72fab4ce")]
  public interface IFolderView
  {
    [PreserveSig]
    int GetCurrentViewMode(ref FOLDERVIEWMODE pViewMode);
    [PreserveSig]
    int SetCurrentViewMode(FOLDERVIEWMODE ViewMode);
    [PreserveSig]
    int GetFolder(ref Guid riid, out IPersistFolder2 ppv);
    [PreserveSig]
    int Item(int iItemIndex, out IntPtr ppidl);
    [PreserveSig]
    int ItemCount(uint uFlags, out int pcItems);
    [PreserveSig]
    int Items(uint uFlags, [In] ref Guid riid, out object ppv);
    [PreserveSig]
    int GetSelectionMarkedItem(out int piItem);
    [PreserveSig]
    int GetFocusedItem(out int piItem);
    [PreserveSig]
    int GetItemPosition(IntPtr pidl, out POINT ppt);
    [PreserveSig]
    int GetSpacing(ref POINT ppt);
    [PreserveSig]
    int GetDefaultSpacing(ref POINT ppt);
    [PreserveSig]
    int GetAutoArrange();
    [PreserveSig]
    int SelectItem(int iItem, int dwFlags);
    [PreserveSig]
    int SelectAndPositionItems(uint cidl, IntPtr apidl, IntPtr apt, int dwFlags);
  }
}
