// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("1AC3D9F0-175C-11d1-95BE-00609797EA4F")]
  public interface IPersistFolder2
  {
    [PreserveSig]
    int GetClassID(out Guid pClassID);
    [PreserveSig]
    int Initialize(IntPtr pidl);
    [PreserveSig]
    int GetCurFolder(out IntPtr ppidl);
  }
}
