// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("000214E3-0000-0000-C000-000000000046")]
  public interface IShellView
  {
    [PreserveSig]
    int GetWindow(out IntPtr phwnd);
    [PreserveSig]
    int ContextSensitiveHelp(bool fEnterMode);
    [PreserveSig]
    int TranslateAccelerator(ref MSG pmsg);
    [PreserveSig]
    int EnableModeless(bool fEnable);
    [PreserveSig]
    int UIActivate(uint uState);
    [PreserveSig]
    int Refresh();
    [PreserveSig]
    int CreateViewWindow(IShellView psvPrevious, ref FOLDERSETTINGS pfs, ref IShellBrowser psb, ref RECT prcView, out IntPtr phWnd);
    [PreserveSig]
    int DestroyViewWindow();
    [PreserveSig]
    int GetCurrentInfo(ref FOLDERSETTINGS lpfs);
    [PreserveSig]
    int AddPropertySheetPages(int dwReserved, IntPtr pfn, IntPtr lparam);
    [PreserveSig]
    int SaveViewState();
    [PreserveSig]
    int SelectItem(IntPtr pidlItem, uint uFlags);
    [PreserveSig]
    int GetItemObject(uint uItem, ref Guid riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppv);
  }
}
