// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin.Interop
{
  using System;
  using System.Runtime.InteropServices;
  using System.Text;
  
  public static class PInvoke
  {
    public static IntPtr CreatePIDL(byte[] data)
    {
      if ((data == null) || (data.Length == 0))
      {
        return IntPtr.Zero;
      }
      int length = data.Length;
      IntPtr zero = IntPtr.Zero;
      try
      {
        zero = Marshal.AllocCoTaskMem(length);
      }
      catch
      {
        return IntPtr.Zero;
      }
      Marshal.Copy(data, 0, zero, length);
      return zero;
    }
    
    public static byte[] GetIDListData(IntPtr pidl)
    {
      if (pidl != IntPtr.Zero)
      {
        uint num = ILGetSize(pidl);
        if (num != 0)
        {
          byte[] destination = new byte[num];
          Marshal.Copy(pidl, destination, 0, (int) num);
          return destination;
        }
      }
      return null;
    }
    
    [DllImport("shell32.dll")]
    public static extern IntPtr ILClone(IntPtr pidl);
    [DllImport("shell32.dll")]
    public static extern uint ILGetSize(IntPtr pidl);
    [DllImport("shlwapi.dll", CharSet=CharSet.Unicode)]
    public static extern int StrRetToBuf(ref STRRET pstr, IntPtr pidl, StringBuilder pszBuf, uint cchBuf);
  }
}
