// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin.Interop
{
  using System;
  using System.Drawing;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  public struct POINT
  {
    public int x;
    public int y;
    public POINT(Point pnt)
    {
      this.x = pnt.X;
      this.y = pnt.Y;
    }
    
    public Point ToPoint()
    {
      return new Point(this.x, this.y);
    }
  }
}
