// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin.Interop
{
  using System;
  using System.Drawing;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Sequential)]
  public struct RECT
  {
    public int left;
    public int top;
    public int right;
    public int bottom;
    public RECT(Rectangle rectangle)
    {
      this.left = rectangle.X;
      this.top = rectangle.Y;
      this.right = rectangle.Right;
      this.bottom = rectangle.Bottom;
    }
    
    public int Width
    {
      get
      {
        return Math.Abs((int) (this.right - this.left));
      }
    }
    public int Height
    {
      get
      {
        return (this.bottom - this.top);
      }
    }
    public Rectangle ToRectangle()
    {
      return new Rectangle(this.left, this.top, this.Width, this.Height);
    }
  }
}
