// Generated by Reflector from c:\program files\qttabbar\QTPluginLib.dll
namespace QTPlugin.Interop
{
  using System;
  using System.Runtime.InteropServices;
  
  [StructLayout(LayoutKind.Explicit, Size=0x10)]
  public struct VARIANT
  {
    [FieldOffset(8)]
    public byte bValue;
    [FieldOffset(8)]
    public double dValue;
    [FieldOffset(8)]
    public float fValue;
    [FieldOffset(8)]
    public int iValue;
    [FieldOffset(8)]
    public long lValue;
    [FieldOffset(8)]
    public IntPtr pValue;
    [FieldOffset(8)]
    public short sValue;
    [FieldOffset(0)]
    public short vt;
    [FieldOffset(2)]
    public short wReserved1;
    [FieldOffset(4)]
    public short wReserved2;
    [FieldOffset(6)]
    public short wReserved3;
  }
}
